apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 992382498205.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:babab2d182463560c6dc537194e39a2719d18884
        ports:
        - containerPort: 80
