apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 992382498205.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:1dca3b6fd9bb27163fa79734a213658c1f756b3b
        ports:
        - containerPort: 80
