apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 992382498205.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:628dfb4a8fe3891d1e4ac9b2b5b66458649213ac
        ports:
        - containerPort: 80
