apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 992382498205.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:097e0b661ac3ef0b2754b1f71dfda681e5dc7900
          ports:
            - containerPort: 5000
