apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:0dd74e7545ce1aa1885df9e37f6aaf6a1742fa47
        ports:
        - containerPort: 80
