apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 992382498205.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:babab2d182463560c6dc537194e39a2719d18884
        ports:
        - containerPort: 80
