apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:617022a141b6fdc9f29c1a03470e9127a5f47b57
        ports:
        - containerPort: 80
