apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 992382498205.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:1dca3b6fd9bb27163fa79734a213658c1f756b3b
        ports:
        - containerPort: 80
